export { connectDB, disconnectDB, isDuplicateKeyError } from "./connection";
export {
  generateImageKey,
  writeImage,
  readImage,
  removeImage,
  removeImages,
  generateAudioKey,
  writeAudio,
  readAudio,
  removeAudio,
  removeAudios,
} from "./gridfs";
export {
  Conversation,
  getOrCreateSession,
  closeSession,
  appendMessage,
  getRecentMessages,
  getOverflowMessages,
  clearConversation,
  trimConversation,
  cleanupOldConversations,
  type IMessage,
  type IConversation,
  type SessionResult,
  type OverflowResult,
} from "./models/conversation";
export {
  PendingFact,
  enqueuePendingFact,
  type IPendingFact,
  type PendingFactInput,
} from "./models/pending-fact";
export {
  Reminder,
  createReminder,
  getPendingReminders,
  markReminderFired,
  listRemindersForChat,
  getRecentlyFiredReminders,
  deleteReminder,
  cleanupFiredReminders,
  type IReminder,
} from "./models/reminder";
export {
  SchedulerState,
  getNextProactiveAt,
  setNextProactiveAt,
  type ISchedulerState,
} from "./models/scheduler-state";
export {
  TokenUsage,
  getUsageSummary,
  getDailyUsage,
  getTotalCost,
  type ITokenUsage,
  type UsageCategory,
  type UsageSummary,
  type DailyUsage,
} from "./models/token-usage";
export {
  LocationHistory,
  storeLocation,
  getLatestLocation,
  getRecentLocations,
  getLocationVisitCount,
  cleanupOldLocations,
  type ILocationHistory,
} from "./models/location-history";
export {
  Routine,
  RoutineLog,
  MAX_ROUTINE_DEPTH,
  createRoutine,
  listRoutinesForChat,
  getRoutineById,
  getRoutineByName,
  updateRoutine,
  updateRoutineIfVersion,
  applyRoutineRefinement,
  recordRoutineGrade,
  clearRefineTracking,
  deleteRoutine,
  getDueRoutines,
  advanceRoutineNextRunAt,
  requestManualRun,
  claimPendingManualRun,
  isRoutineRunning,
  createRoutineLog,
  completeRoutineLog,
  failRoutineLog,
  getRoutineLogs,
  countRealRunsSince,
  getRoutineHealth,
  routineNeedsAttention,
  listChatIdsWithRoutines,
  listRoutinesAwaitingPostRefineReview,
  cleanupOldRoutineLogs,
  resetStaleRunningRoutineLogs,
  NO_REPORT_SENTINEL,
  type IRoutine,
  type IRoutineLog,
  type IRoutineParameter,
  type RoutineParameterType,
  type RoutineInput,
  type RoutinePurity,
  type RoutineHealth,
} from "./models/routine";
export {
  PendingConfirmation,
  createPendingConfirmation,
  getPendingConfirmation,
  setPromptMessageId,
  resolvePendingConfirmation,
  attachResultText,
  listPendingConfirmations,
  type IPendingConfirmation,
  type PendingConfirmationStatus,
  type PendingConfirmationOrigin,
  type CreatePendingConfirmationInput,
} from "./models/pending-confirmation";
export {
  RoutineProposalDecision,
  recordProposalDecision,
  isRecentlyDeclined,
  type IRoutineProposalDecision,
  type ProposalVerdict,
  type RecordProposalDecisionOptions,
} from "./models/routine-proposal";
export {
  Watcher,
  WatcherLog,
  createWatcher,
  listWatchersForChat,
  getWatcherById,
  getWatcherByName,
  updateWatcher,
  deleteWatcher,
  archiveWatcher,
  archiveExpiredWatchers,
  getDueWatchers,
  advanceWatcherNextRunAt,
  recordWatcherObservation,
  recordWatcherStateOnly,
  requestManualWatcherRun,
  claimPendingManualWatcherRun,
  isWatcherRunning,
  createWatcherLog,
  completeWatcherLog,
  failWatcherLog,
  getWatcherLogs,
  cleanupOldWatcherLogs,
  resetStaleRunningWatcherLogs,
  defaultExpiresAt,
  type IWatcher,
  type IWatcherLog,
  type WatcherInput,
} from "./models/watcher";
