import type { EnvSpec, VarInfo } from "./types.js";

/**
 * Pure renderers — given a spec, produce the generated-artifact strings.
 * Filesystem access, prettier formatting, and --check diffing live in the
 * workspace-level driver (scripts/env/generate.ts), not here, so these stay
 * trivially testable and the package stays dependency-light.
 */

const GENERATED_NOTE = "Generated by @kagami/env — edit src/env.ts and run `npm run env:gen`.";

function exampleValue(info: VarInfo): string {
  if (info.meta.secret) return "";
  return info.meta.example ?? info.defaultValue ?? "";
}

/** `.env.example` for one app, in declaration order, grouped by `meta.group`. */
export function renderEnvExample(spec: EnvSpec<unknown>): string {
  const lines: string[] = [`# ${spec.service}/${spec.component} — ${GENERATED_NOTE}`];
  let currentGroup: string | undefined;

  for (const info of spec.keys) {
    lines.push("");
    if (info.meta.group !== currentGroup) {
      currentGroup = info.meta.group;
      if (currentGroup) {
        lines.push(`# === ${currentGroup} ===`);
        lines.push("");
      }
    }
    for (const docLine of info.meta.doc.split("\n")) {
      lines.push(docLine === "" ? "#" : `# ${docLine}`);
    }
    const value = exampleValue(info);
    // Optional vars with nothing to suggest render commented-out so the
    // template documents them without turning them on; `recommended` opts a
    // var back in (optional at boot, but the template should ship it on).
    const commented = !info.required && info.defaultValue === undefined && !info.meta.recommended;
    lines.push(`${commented ? "# " : ""}${info.key}=${value}`);
  }

  for (const [alias, canonical] of Object.entries(spec.aliases)) {
    lines.push("");
    lines.push(`# ${alias} is a legacy alias for ${canonical} (used when ${canonical} is unset).`);
  }

  return `${lines.join("\n")}\n`;
}

function escapeTableCell(text: string): string {
  return text.replaceAll("|", "\\|");
}

/**
 * The doc's first sentence (newlines collapsed) — keeps table cells readable
 * instead of cutting a wrapped line mid-sentence. Avoid `". "`-containing
 * abbreviations in a var's opening sentence.
 */
function firstSentence(doc: string): string {
  const flattened = doc.replaceAll("\n", " ").trim();
  const cut = flattened.indexOf(". ");
  return cut === -1 ? flattened : flattened.slice(0, cut + 1);
}

/** Markdown table for the project's docs/configuration.md. */
export function renderConfigDocTable(spec: EnvSpec<unknown>): string {
  const rows = spec.keys.map((info) => {
    const purpose = escapeTableCell(firstSentence(info.meta.doc));
    const defaultCell = info.defaultValue !== undefined ? `\`${info.defaultValue}\`` : "—";
    return `| \`${info.key}\` | ${info.required ? "yes" : "no"} | ${defaultCell} | ${purpose} |`;
  });
  return [
    `<!-- ${GENERATED_NOTE} -->`,
    "",
    "| Var | Required | Default | Purpose |",
    "| --- | -------- | ------- | ------- |",
    ...rows,
  ].join("\n");
}

/**
 * Replace the payload between `<!-- kagami-env:begin <id> -->` and
 * `<!-- kagami-env:end <id> -->` markers. Throws when markers are missing —
 * marker placement is a one-time manual act so generation can never clobber
 * surrounding hand-written prose.
 */
export function replaceBetweenMarkers(content: string, id: string, payload: string): string {
  const begin = `<!-- kagami-env:begin ${id} -->`;
  const end = `<!-- kagami-env:end ${id} -->`;
  const beginIndex = content.indexOf(begin);
  const endIndex = content.indexOf(end);
  if (beginIndex === -1 || endIndex === -1 || endIndex < beginIndex) {
    throw new Error(`@kagami/env: markers for '${id}' not found (or out of order)`);
  }
  return `${content.slice(0, beginIndex + begin.length)}\n\n${payload.trimEnd()}\n\n${content.slice(endIndex)}`;
}

/**
 * Turborepo Package Configuration declaring this app's env keys on the tasks
 * that actually execute it. Turbo 2 runs in strict env mode by default, so an
 * undeclared var is filtered out of the task's environment entirely — this is
 * the fix for shell-set vars silently never reaching apps.
 */
export function renderTurboPackageConfig(
  spec: EnvSpec<unknown>,
  tasks: string[],
): Record<string, unknown> {
  const env = [...spec.keyNames, ...Object.keys(spec.aliases)].sort();
  return {
    $schema: "https://turbo.build/schema.json",
    extends: ["//"],
    tasks: Object.fromEntries(tasks.map((task) => [task, { env }])),
  };
}
