import { describe, expect, it } from "vitest";
import { z } from "zod";
import {
  defineEnv,
  renderConfigDocTable,
  renderEnvExample,
  renderTurboPackageConfig,
  replaceBetweenMarkers,
} from "../src/index.js";

function sampleSpec() {
  return defineEnv({
    service: "sample",
    component: "api",
    aliases: { MODEL: "LLM_MODEL" },
    vars: {
      MONGODB_URI: z
        .string()
        .regex(/^mongodb:\/\//)
        .meta({ doc: "Mongo connection string.", example: "mongodb://127.0.0.1:27017/sample" }),
      API_TOKEN: z.string().min(16).meta({ doc: "Bearer for the vend surface.", secret: true }),
      LLM_MODEL: z.string().default("claude-sonnet-4-6").meta({ doc: "Chat model id." }),
      KANSOKU_URL: z.string().url().optional().meta({
        doc: "Observability target.\nBoth Kansoku vars or neither.",
        example: "https://api.kansoku.localhost",
        group: "Kansoku (observability)",
      }),
    },
  });
}

describe("renderEnvExample", () => {
  it("renders docs as comments, secrets blank, optionals commented, groups as headers", () => {
    const text = renderEnvExample(sampleSpec());
    expect(text).toContain("# sample/api — Generated by @kagami/env");
    // Required with example → uncommented with the example value.
    expect(text).toContain(
      "# Mongo connection string.\nMONGODB_URI=mongodb://127.0.0.1:27017/sample",
    );
    // Required secret → uncommented, blank value.
    expect(text).toContain("API_TOKEN=\n");
    // Default → shown inline.
    expect(text).toContain("LLM_MODEL=claude-sonnet-4-6");
    // Optional without default → commented out, multi-line doc preserved.
    expect(text).toContain("# === Kansoku (observability) ===");
    expect(text).toContain(
      "# Observability target.\n# Both Kansoku vars or neither.\n# KANSOKU_URL=https://api.kansoku.localhost",
    );
    // Alias note at the bottom.
    expect(text).toContain("# MODEL is a legacy alias for LLM_MODEL");
    expect(text.endsWith("\n")).toBe(true);
  });
});

describe("renderConfigDocTable", () => {
  it("renders one row per var with required/default/first-doc-line", () => {
    const table = renderConfigDocTable(sampleSpec());
    expect(table).toContain("| `MONGODB_URI` | yes | — | Mongo connection string. |");
    expect(table).toContain("| `LLM_MODEL` | no | `claude-sonnet-4-6` | Chat model id. |");
    expect(table).toContain("| `KANSOKU_URL` | no | — | Observability target. |");
  });
});

describe("replaceBetweenMarkers", () => {
  it("replaces only the marked span and leaves surrounding prose alone", () => {
    const original = [
      "# Configuration",
      "",
      "Hand-written intro.",
      "",
      "<!-- kagami-env:begin sample/api -->",
      "stale",
      "<!-- kagami-env:end sample/api -->",
      "",
      "Hand-written outro.",
    ].join("\n");
    const updated = replaceBetweenMarkers(original, "sample/api", "FRESH");
    expect(updated).toContain("Hand-written intro.");
    expect(updated).toContain("Hand-written outro.");
    expect(updated).toContain(
      "<!-- kagami-env:begin sample/api -->\n\nFRESH\n\n<!-- kagami-env:end sample/api -->",
    );
    expect(updated).not.toContain("stale");
  });

  it("throws when the markers are missing so prose can never be clobbered", () => {
    expect(() => replaceBetweenMarkers("no markers here", "sample/api", "x")).toThrow(
      /sample\/api/,
    );
  });
});

describe("renderTurboPackageConfig", () => {
  it("declares every key (and alias) on the requested tasks, sorted", () => {
    const config = renderTurboPackageConfig(sampleSpec(), ["dev", "test"]);
    expect(config).toEqual({
      $schema: "https://turbo.build/schema.json",
      extends: ["//"],
      tasks: {
        dev: { env: ["API_TOKEN", "KANSOKU_URL", "LLM_MODEL", "MODEL", "MONGODB_URI"] },
        test: { env: ["API_TOKEN", "KANSOKU_URL", "LLM_MODEL", "MODEL", "MONGODB_URI"] },
      },
    });
  });
});
